Add language verification
Add verification to make sure you didn't miss running npm run lang:build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,3 +53,35 @@ jobs:
         run: |
           npm install d2l-license-checker --no-save
           npx license-checker-ci
+  verify-languages:
+    name: Verify Languages
+    timeout-minutes: 5
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: Brightspace/third-party-actions@actions/checkout
+      - name: Verify Languages
+        run: |
+          status=0
+          for lang in ./lang/*.json
+          do
+            tmpLang="$(basename $lang)"
+            echo "Verifying: $tmpLang"
+            tmpLang="./build/lang/${tmpLang/json/js.expected}"
+            printf "export const val = " | cat -s - "$lang" > "$tmpLang"
+            sed -i 's/\}\s*$/\};/' "$tmpLang"
+            diff -b -B "${tmpLang%.expected}" "$tmpLang"
+            if [ $? -ne 0 ]; then
+              echo "Failed: $tmpLang"
+              status=1
+            fi
+            rm "$tmpLang"
+          done
+          if [ $status -ne 0 ]; then
+            echo "Lang files do not match expected generated serge files" 1>&2
+            echo "Did you forget to run `npm run lang:build`?" 1>&2
+          else
+            echo "Lang files do match expected generated serge files"
+          fi
+          exit $status
+
